Add extra integration tests + move to DPE workflow

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -8,3 +8,15 @@ bases:
     run-on:
     - name: "ubuntu"
       channel: "20.04"
+
+parts:
+  charm:
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build-dev" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
+    charm-strict-dependencies: true
+    charm-entrypoint: src/charm.py
